version: "3.9"
services:
  api:
    build: api/
    ports:
      - "3000:3000"
  database:
    image: "mongo:latest"
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_DATABASE=main
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
